language: node_js
node_js:
  - lts/*
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE houseHuntingFix;" -U postgres
  - psql -c "CREATE USER house WITH PASSWORD '0000';" -U postgres
  - 'npm run build:db'
env:
  global:
    - PGPORT=5432
test:
  adapter: postgresql
  database: houseHuntingFix

  